# Generated by Django 3.1 on 2020-08-26 10:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chat_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='req_channel_name',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='res_channel_name',
        ),
        migrations.AddField(
            model_name='chat_message',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
